const types = {
   
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
   
    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',
    
    CREATE_TRANSACTION_START: 'CREATE_TRANSACTION_START',
    CREATE_TRANSACTION_SUCCESS: 'CREATE_TRANSACTION_SUCCESS',
    CREATE_TRANSACTION_FAILED: 'CREATE_TRANSACTION_FAILED',
  
    SAVE_LOGIN: 'SAVE_LOGIN',
  
    LOGOUT: 'LOGOUT',



  };
  
  export default types;
  